const ERROR_MERGE = 'ERROR_MERGE';
const ERROR_SPLIT = 'ERROR_SPLIT';
const ERROR_COMPRESS = 'ERROR_COMPRESS';
const ERROR_CONVERT = 'ERROR_CONVERT';
export { ERROR_MERGE, ERROR_SPLIT, ERROR_COMPRESS, ERROR_CONVERT };
