const OPERATION_MERGE = 'MERGE';
const OPRATION_SPLIT = 'SPLIT';
const OPRATION_COMPRESS = 'COMPRESS';
const OPRATION_CONVERT_WORD_TO_PDF = 'CONVERT_WORD_TO_PDF';
const OPRATION_CONVERT_PPT_TO_PDF = 'CONVERT_PPT_TO_PDF';
const OPRATION_CONVERT_EXCEL_TO_PDF = 'CONVERT_EXCEL_TO_PDF';
const OPRATION_CONVERT_PDF_TO_WORD = 'CONVERT_PDF_TO_WORD';
const OPRATION_CONVERT_PDF_TO_PPT = 'CONVERT_PDF_TO_PPT';
const OPRATION_CONVERT_PDF_TO_EXCEL = 'CONVERT_PDF_TO_EXCEL';

const OPRATION_CONVERT_PDF_TO_IMAGE = 'CONVERT_PPT_TO_IMAGE';
const OPRATION_CONVERT_IMAGE_TO_PDF = 'CONVERT_IMAGE_TO_PPT';

export {
  OPERATION_MERGE,
  OPRATION_SPLIT,
  OPRATION_CONVERT_WORD_TO_PDF,
  OPRATION_CONVERT_PPT_TO_PDF,
  OPRATION_CONVERT_EXCEL_TO_PDF,
  OPRATION_CONVERT_PDF_TO_WORD,
  OPRATION_CONVERT_PDF_TO_PPT,
  OPRATION_CONVERT_PDF_TO_EXCEL,
  OPRATION_COMPRESS,
  OPRATION_CONVERT_PDF_TO_IMAGE,
  OPRATION_CONVERT_IMAGE_TO_PDF,
};
